### ISSUE TITLE
 Rules file not found. in /Users/alexMac/Projects/php-to-pdf/petrovich-php/Petrovich.php:30

### ISSUE THREAD

**Issue by alexTitakoff** [petrovich/petrovich-php#14]
Привет!

А где файл правил?
![BBCB9D1E-3E6B-4C56-AF0E-B074252D911F](https://user-images.githubusercontent.com/15850419/149145973-e34e589c-e33f-40e8-b385-c983b536cd60.png)

**Comment by alexTitakoff** [comment]
А все нашел)
Только при клонировании их нет вроде бы

**Comment by alexTitakoff** [comment]
они в другой репе получается?

**Comment by mikhail-barg** [comment]
субмодули же
